on:
  push:
    branches: [ main ]
jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
